### ISSUE TITLE
mycomponent.jsx changes not detected and re-compiled on `gulp watch`

### ISSUE THREAD

**Issue by cadorn** [Granze/react-starterify#10]
When running via `gulp watch` changes to `mycomponent.jsx` are not reloaded.

Any idea as to what could be wrong?

**Comment by Granze** [comment]
Hey that's weird, I've just tried and it works on my computer™
Are you getting some kind of error in the console? Let me know, thanks.

**Comment by cadorn** [comment]
No errors. I'll have to dig deeper some other time.

**Comment by jpdesigndev** [comment]
Same issue here. No idea where to go to fix. No errors. @Granze any ideas?
