### ISSUE TITLE
Failed to load external module babel-core/register

### ISSUE THREAD

**Issue by dbertella** [Granze/react-starterify#18]
I had this error after running gulp the first time, i've installed babel-core and now looks ok.
Did you have the same issue?
Anyway for me this solved the thing: npm install --save-dev babel-core

**Comment by Granze** [comment]
Tried a fresh install right now and it works. :|

**Comment by dbertella** [comment]
Dunno why, it may be a local environment issue then. I'll try a fresh
install in another computer.

2015-10-03 23:27 GMT+02:00 Maurizio Mangione <notifications@github.com>:

> Tried a fresh install right now and it works. :|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Granze/react-starterify/issues/18#issuecomment-145291999>
> .
>



-- 
Daniele Bertella
*Front end developer *

+39.340.490.57.80
info@danielebertella.com
LinkedIn: danielebertella <http://it.linkedin.com/in/danielebertella/>
Twitter: _denb <https://twitter.com/_denb>
www.danielebertella.com

**Comment by Granze** [comment]
Let me know, thanks! ;)

**Comment by maxknu** [comment]
Had the same "error" with Babel-core 
- "Failed to load external module babel-core/register"
- Requiring external module babel/register

But, it started anyway. i had my install inside a fresh-started dev VM with only nodejs and gulp installed.

**Comment by Granze** [comment]
Ok, I'll try to find out what's the problem later.

**Comment by Granze** [comment]
It should be ok now.
Probably because I had babel installed globally on both my machines it was working.

Let me know if it is working for you as well, thanks!

**Comment by bnhovde** [comment]
FYI: I'm experiencing this error now (clean install). I've used your build across multiple environments, but only my work machine i get the error.

I'll post back here if I work it out.

**Comment by Granze** [comment]
@bnhovde Yes, let me know, please.
