### ISSUE TITLE
gulp-gh-pages for convenient deployment?

### ISSUE THREAD

**Issue by holmesworcester** [Granze/react-starterify#28]
When getting started as a beginner it's pretty game-changing to know exactly how/where you're going to deploy your work once you get started.

It took me a bit of futzing around thinking about Heroku before I found this recommendation: 
https://www.reddit.com/r/reactjs/comments/3pyfge/deploying_my_first_react_app/

Then I used this tool though I had to install it in a slightly different way: https://www.npmjs.com/package/gulp-gh-pages

This got me the intended result, which was that "npm run deploy" would put my site at a github pages URL. 

If the intended audience here is extreme beginners, to me it seems like it would be awesome to add this in. Should I submit a pull request for what I did? (Warning: this is one of my first times touching JavaScript and I'm really inept).

A slight improvement would be to have the deploy script tell you the URL on gh pages to look at to see your deployed work, so you don't have to go around googling things about github pages.

**Comment by Granze** [comment]
Nice idea @holmesworcester! I'll work on this.

**Comment by Granze** [comment]
Done, check the latest release!

**Comment by gmarceau** [comment]
awesomesauce :+1:

**Comment by holmesworcester** [comment]
Nice, thanks!

–Holmes
