### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by scpeterson** [Granze/react-starterify#3]
I cloned the repository and ran "gulp watch," but received the message "cannot find module 'liftoff' from module.js:340.  Once I ran "npm install -g liftoff," gulp watch ran just fine.

**Comment by Granze** [comment]
Hi @scpeterson, can you please test the last version? (v0.0.7)

Thanks

**Comment by scpeterson** [comment]
I deleted the repository I had on disk and cloned a fresh repository.  I ran "npm install" and then ran "gulp watch."  I no longer get the error I reported above, so all apperas to be well.  I should report that I have the same OS as stated previously, but am now on Node v0.10.36 with npm 1.4.28.

Thank you for your help!

**Comment by Granze** [comment]
Nice, thank you!
