### ISSUE TITLE
Server side code

### ISSUE THREAD

**Issue by andreasi** [Granze/react-starterify#34]
Hi everyone. 
I really love the kit and I want to use it for my next application, so I'm still experimenting. I'm kind of new to nodejs. Any idea how I could include server side code (react, mongoose) within react starterify.
Thanks

**Comment by Granze** [comment]
Hi, honestly I haven't  used the server rendering in React yet, so I'm not an expert on this topic.
I found [this guide](https://github.com/mhart/react-server-example) that may helps.

**Comment by andreasi** [comment]
Hi.
Thank you for your response. This is not an actual issue but I couldn't find any other way to communicate with you. By server side code I don't mean server side rendering using react. What I mean is having an API on the same code base.  Right now the kit runs a server on localhost:3000 if I'm correct. My question is how can I have for example a server.js running express for my API calls. I know that probably this is not how and why the kit was designed for, but I don't know if that would be a could idea. 
Thank you for your time!

**Comment by Granze** [comment]
Oh I see. Well, there are really many options here. 
[Relay](https://facebook.github.io/relay/) is the way FB do that but, of course, you need to use GraphQL.

If you need a simple way to get some data from the server, you can do it in the `componentDidMount` function as explained [here](https://facebook.github.io/react/tips/initial-ajax.html).

For more complex (real world) applications, you will probably use one of the available Flux implementations like [Redux](https://github.com/reactjs/redux). This is obviously not the only way to do it and there are lots of discussions on the topic, like [this one](http://www.infoq.com/articles/no-more-mvc-frameworks).

React Starterify, wants to be minimal and less opinionated as possible, for that reason, it doesn't include any of these solutions.
