### ISSUE TITLE
Cache for watchify

### ISSUE THREAD

**Issue by HugoMcPhee** [Granze/react-starterify#39]
Hi, Have you considered adding 
cache: {}, packageCache: {}
to "customOpts" in the gulp file?

After adding the two options, my compile times went from around 5 seconds to around 1 second
Thanks

**Comment by Granze** [comment]
Uh, nice catch! I've just [added](https://github.com/Granze/react-starterify/blob/master/gulpfile.babel.js#L41-L42) them.

Thanks :)
