### ISSUE TITLE
JSX tranform/ES6 support

### ISSUE THREAD

**Issue by timarney** [Granze/react-starterify#4]
Does something need to be configured in the Gulp file or package.json to enable ES6 support?

https://www.npmjs.com/package/reactify

{
    "name": "my-package",
    "browserify": {
        "transform": [
            ["reactify", {"es6": true}]
        ]
    }
}

**Comment by Granze** [comment]
Hi @timarney, I just released version 0.0.6. The new version includes 6to5 instead of reactify for a better ES6 support. Now ES6 should work out of box.

Let me know what you think. Thanks!

**Comment by timarney** [comment]
Nice!  Works great.  Happy to see your using 6to5 now.
