### ISSUE TITLE
Test coverage with Jest

### ISSUE THREAD

**Issue by khanghoang** [Granze/react-starterify#5]
Hi there, 

Is there any way to run test coverage? 
I saw it in the Facebook/Jest repo https://github.com/facebook/jest/pull/178

**Comment by Granze** [comment]
Hey, not yet but I'll do this ASAP.

**Comment by khanghoang** [comment]
Okie, then i should close this issue, please update when it's done.

**Comment by Granze** [comment]
Of course, I will.
Thanks!
