### ISSUE TITLE
Gulpfile

### ISSUE THREAD

**Issue by ktmn** [Granze/react-starterify#9]
Maybe it's just me and my lack of experience, but if the gulpfile.js was heavily commented I'd maybe have a better understanding what's going on there, how to add, remove or replace files and commands.

**Comment by Granze** [comment]
Hi @ktmn, I'm not the kind of person that like comments in code at all.
I think my gulpfile is really simple to understand but, if it's still cryptic for you, then you probably need to take a look at the [gulp documentation](https://github.com/gulpjs/gulp/tree/master/docs) or at this [good article](http://markgoodyear.com/2014/01/getting-started-with-gulp/). Hope this helps. :smiley:
